### ISSUE TITLE
error at line 112 

### ISSUE THREAD

**Issue by keesbran** [joker-b/ChartThrob#1]
Hi,

Today at a digital negatives workshop I gave 3 people installed the latest version of chartthrob and all installations (2x windows PS 5.1, 1x mac PS CC 2014) gave an error at calling the script (line 112).
My own installion works fine. We all used the same IP (studio wifi network).
Could this be something with the google analytics call, new in this version?

best regards,

Kees Brandenburg | polychrome.nl
middelburg, netherlands

**Comment by joker-b** [comment]
forgot to close this loooong ago
